-- Shared editorial workspace for "Семейные маршруты по Кеми с Первыми".
-- Safe to run more than once in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'participant' check (role in ('participant', 'moderator', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.points (
  id text primary key,
  route_order integer,
  chapter text not null default 'railway',
  title text not null,
  short_title text,
  latitude double precision,
  longitude double precision,
  coordinate_status text not null default 'needs-check' check (coordinate_status in ('verified', 'needs-check')),
  status text not null default 'research' check (status in ('research', 'draft', 'published', 'archived')),
  content jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.routes (
  id text primary key,
  title text not null,
  travel_mode text not null default 'walking' check (travel_mode in ('walking', 'manual')),
  status text not null default 'published' check (status in ('draft', 'published', 'archived')),
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

insert into public.routes (id, title, travel_mode, status)
values ('main', 'Большой экскурсионный маршрут по Кеми', 'walking', 'published')
on conflict (id) do nothing;

create table if not exists public.route_waypoints (
  id uuid primary key default gen_random_uuid(),
  route_id text not null references public.routes(id) on delete cascade,
  position integer not null,
  point_id text references public.points(id) on delete set null,
  latitude double precision not null,
  longitude double precision not null,
  kind text not null default 'via' check (kind in ('stop', 'via')),
  created_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  unique (route_id, position)
);

create table if not exists public.photos (
  id uuid primary key default gen_random_uuid(),
  point_id text not null references public.points(id) on delete cascade,
  title text not null,
  caption text not null default '',
  shot_date text,
  author text,
  source text,
  rights_status text,
  storage_path text not null unique,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  created_by uuid not null references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.point_revisions (
  id bigint generated by default as identity primary key,
  point_id text not null,
  changed_by uuid references auth.users(id),
  previous_value jsonb,
  new_value jsonb,
  changed_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists points_set_updated_at on public.points;
create trigger points_set_updated_at before update on public.points
for each row execute function public.set_updated_at();

drop trigger if exists photos_set_updated_at on public.photos;
create trigger photos_set_updated_at before update on public.photos
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role is distinct from old.role
    and auth.uid() is not null
    and public.current_user_role() <> 'admin' then
    raise exception 'Only an administrator can change participant roles';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_protect_role on public.profiles;
create trigger profiles_protect_role before update on public.profiles
for each row execute function public.protect_profile_role();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.audit_point_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.point_revisions (point_id, changed_by, previous_value, new_value)
  values (new.id, auth.uid(), to_jsonb(old), to_jsonb(new));
  return new;
end;
$$;

drop trigger if exists points_audit_change on public.points;
create trigger points_audit_change
after update on public.points
for each row execute function public.audit_point_change();

create or replace function public.replace_main_route_waypoints(p_waypoints jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  delete from public.route_waypoints where route_id = 'main';

  insert into public.route_waypoints (
    route_id, position, point_id, latitude, longitude, kind, created_by
  )
  select
    'main',
    ordinality::integer,
    nullif(item ->> 'pointId', ''),
    (item ->> 'lat')::double precision,
    (item ->> 'lng')::double precision,
    case when item ->> 'kind' = 'stop' then 'stop' else 'via' end,
    auth.uid()
  from jsonb_array_elements(p_waypoints) with ordinality as items(item, ordinality);

  update public.routes
  set updated_by = auth.uid(), updated_at = now()
  where id = 'main';
end;
$$;

alter table public.profiles enable row level security;
alter table public.points enable row level security;
alter table public.routes enable row level security;
alter table public.route_waypoints enable row level security;
alter table public.photos enable row level security;
alter table public.point_revisions enable row level security;

drop policy if exists "profiles read own" on public.profiles;
create policy "profiles read own" on public.profiles for select to authenticated
using (id = auth.uid() or public.current_user_role() in ('moderator', 'admin'));

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own" on public.profiles for update to authenticated
using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "profiles create own" on public.profiles;
create policy "profiles create own" on public.profiles for insert to authenticated
with check (id = auth.uid() and role = 'participant');

drop policy if exists "points public read" on public.points;
create policy "points public read" on public.points for select to anon, authenticated
using (status = 'published' or auth.uid() is not null);

drop policy if exists "participants create points" on public.points;
create policy "participants create points" on public.points for insert to authenticated
with check (created_by = auth.uid() and updated_by = auth.uid());

drop policy if exists "participants edit points" on public.points;
create policy "participants edit points" on public.points for update to authenticated
using (true) with check (updated_by = auth.uid());

drop policy if exists "admins delete points" on public.points;
create policy "admins delete points" on public.points for delete to authenticated
using (public.current_user_role() = 'admin');

drop policy if exists "routes public read" on public.routes;
create policy "routes public read" on public.routes for select to anon, authenticated using (status <> 'archived');

drop policy if exists "participants edit routes" on public.routes;
create policy "participants edit routes" on public.routes for update to authenticated
using (true) with check (updated_by = auth.uid());

drop policy if exists "waypoints public read" on public.route_waypoints;
create policy "waypoints public read" on public.route_waypoints for select to anon, authenticated using (true);

drop policy if exists "participants create waypoints" on public.route_waypoints;
create policy "participants create waypoints" on public.route_waypoints for insert to authenticated
with check (created_by = auth.uid());

drop policy if exists "participants edit waypoints" on public.route_waypoints;
create policy "participants edit waypoints" on public.route_waypoints for update to authenticated
using (true) with check (true);

drop policy if exists "participants delete waypoints" on public.route_waypoints;
create policy "participants delete waypoints" on public.route_waypoints for delete to authenticated using (true);

drop policy if exists "photos public read published" on public.photos;
create policy "photos public read published" on public.photos for select to anon
using (status = 'published');

drop policy if exists "participants read photos" on public.photos;
create policy "participants read photos" on public.photos for select to authenticated using (true);

drop policy if exists "participants create photos" on public.photos;
create policy "participants create photos" on public.photos for insert to authenticated
with check (created_by = auth.uid());

drop policy if exists "participants edit photos" on public.photos;
create policy "participants edit photos" on public.photos for update to authenticated
using (true) with check (updated_by = auth.uid());

drop policy if exists "owners delete photos" on public.photos;
create policy "owners delete photos" on public.photos for delete to authenticated
using (created_by = auth.uid() or public.current_user_role() in ('moderator', 'admin'));

drop policy if exists "participants read revisions" on public.point_revisions;
create policy "participants read revisions" on public.point_revisions for select to authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on public.points, public.routes, public.route_waypoints to anon;
grant select on public.points, public.routes, public.route_waypoints, public.photos, public.profiles, public.point_revisions to authenticated;
grant insert, update on public.points, public.photos to authenticated;
grant insert, update on public.profiles to authenticated;
grant update on public.routes to authenticated;
grant insert, update, delete on public.route_waypoints to authenticated;
grant delete on public.points, public.photos to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.replace_main_route_waypoints(jsonb) to authenticated;
grant execute on function public.current_user_role() to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('point-photos', 'point-photos', true, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public can view point photos" on storage.objects;
create policy "public can view point photos" on storage.objects for select to anon, authenticated
using (bucket_id = 'point-photos');

drop policy if exists "participants upload point photos" on storage.objects;
create policy "participants upload point photos" on storage.objects for insert to authenticated
with check (bucket_id = 'point-photos' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "owners update point photos" on storage.objects;
create policy "owners update point photos" on storage.objects for update to authenticated
using (bucket_id = 'point-photos' and owner_id = auth.uid()::text)
with check (bucket_id = 'point-photos' and owner_id = auth.uid()::text);

drop policy if exists "owners delete point photos" on storage.objects;
create policy "owners delete point photos" on storage.objects for delete to authenticated
using (bucket_id = 'point-photos' and owner_id = auth.uid()::text);

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'points') then
    alter publication supabase_realtime add table public.points;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'photos') then
    alter publication supabase_realtime add table public.photos;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'route_waypoints') then
    alter publication supabase_realtime add table public.route_waypoints;
  end if;
end
$$;
